const basePath = process.env.NODE_ENV === 'production' ? '/homepage' : '';

export default function Head() {
  return (
    <>
      <title>ProfessorYohSecondYearSeminar</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={`${basePath}/favicon.ico`} />
    </>
  );
}
